language: java
sudo: required
dist: trusty
cache:
  directories:
  - "${HOME}/.m2/repository"
env:
  global:
  - PS1=">"
before_install:
- openssl aes-256-cbc -K $encrypted_2e6b62dd1b86_key -iv $encrypted_2e6b62dd1b86_iv
  -in key.gpg.enc -out key.gpg -d
- wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.tar.gz
- tar -zxvf apache-maven-3.6.3-bin.tar.gz
- export MAVEN_HOME=`pwd`"/apache-maven-3.6.3"
- export PATH=${MAVEN_HOME}/bin:$PATH
- wget https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.8.30/linux/x86_64/ibm-java-sdk-8.0-8.30-linux-x86_64.tgz
- tar -zxvf ibm-java-sdk-8.0-8.30-linux-x86_64.tgz
- export JAVA_HOME=ibm-java-x86_64-80
- export PATH=${JAVA_HOME}/bin:${PATH}
- mvn --version
- java -version
install: true
script:
- travis_wait 120 bash ./travis-build.sh
before_cache:
- rm -fr ${HOME}/.m2/repository/com/ibm/ai/systemt
