language: java
# jdk:
# - oraclejdk8

# The test requires more than 6GB memory, so Ubuntu 14.04 VM which has 7.5 GB memory is used.
# See https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
sudo: required
dist: trusty

# addons:
#   apt:
#     packages:
#     - rpm

cache:
  directories:
  - ${HOME}/.m2/repository

env:
  global:
  # Use this to avoid a issue when installing IBM JDK (LAX installer issue)
  - PS1=">"

before_install:
# Install IBM JDK8 and compatible maven version
  - wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
  - tar -zxvf apache-maven-3.9.9-bin.tar.gz
  - export MAVEN_HOME=`pwd`"/apache-maven-3.9.9"
  - wget https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.8.30/linux/x86_64/ibm-java-sdk-8.0-8.30-linux-x86_64.tgz
  - tar -zxvf ibm-java-sdk-8.0-8.30-linux-x86_64.tgz
  - export JAVA_HOME=ibm-java-x86_64-80
  - export PATH=${JAVA_HOME}/bin:${PATH}

install: true

script:
- travis_wait 120 bash ./travis-build.sh

before_cache:
- rm -fr ${HOME}/.m2/repository/com/ibm/ai/systemt
