/*******************************************************************************
 * Copyright IBM
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 *******************************************************************************/
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.19 at 04:26:09 PM IST
//

package com.ibm.avatar.aql.tam;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.ibm.avatar.aql.tam package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _ModuleMetadata_QNAME =
      new QName("http://www.ibm.com/aql", "module-metadata");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: com.ibm.avatar.aql.tam
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link InputType.Param }
   */
  public InputType.Param createInputTypeParam() {
    return new InputType.Param();
  }

  /**
   * Create an instance of {@link TableMetadataImpl }
   */
  public TableMetadataImpl createTableMetadataImpl() {
    return new TableMetadataImpl();
  }

  /**
   * Create an instance of {@link ModuleMetadataImpl.Dictionaries }
   */
  public ModuleMetadataImpl.Dictionaries createModuleMetadataImplDictionaries() {
    return new ModuleMetadataImpl.Dictionaries();
  }

  /**
   * Create an instance of {@link InputType }
   */
  public InputType createInputType() {
    return new InputType();
  }

  /**
   * Create an instance of {@link SchemaType }
   */
  public SchemaType createSchemaType() {
    return new SchemaType();
  }

  /**
   * Create an instance of {@link ModuleMetadataImpl.Tables }
   */
  public ModuleMetadataImpl.Tables createModuleMetadataImplTables() {
    return new ModuleMetadataImpl.Tables();
  }

  /**
   * Create an instance of {@link DictionaryMetadataImpl }
   */
  public DictionaryMetadataImpl createDictionaryMetadataImpl() {
    return new DictionaryMetadataImpl();
  }

  /**
   * Create an instance of {@link ModuleMetadataImpl.Views }
   */
  public ModuleMetadataImpl.Views createModuleMetadataImplViews() {
    return new ModuleMetadataImpl.Views();
  }

  /**
   * Create an instance of {@link ViewMetadataImpl }
   */
  public ViewMetadataImpl createViewMetadataImpl() {
    return new ViewMetadataImpl();
  }

  /**
   * Create an instance of {@link FunctionMetadataImpl }
   */
  public FunctionMetadataImpl createFunctionMetadataImpl() {
    return new FunctionMetadataImpl();
  }

  /**
   * Create an instance of {@link SchemaType.Column }
   */
  public SchemaType.Column createSchemaTypeColumn() {
    return new SchemaType.Column();
  }

  /**
   * Create an instance of {@link ModuleMetadataImpl }
   */
  public ModuleMetadataImpl createModuleMetadataImpl() {
    return new ModuleMetadataImpl();
  }

  /**
   * Create an instance of {@link ModuleMetadataImpl.Functions }
   */
  public ModuleMetadataImpl.Functions createModuleMetadataImplFunctions() {
    return new ModuleMetadataImpl.Functions();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link ModuleMetadataImpl }{@code >}
   */
  @XmlElementDecl(namespace = "http://www.ibm.com/aql", name = "module-metadata")
  public JAXBElement<ModuleMetadataImpl> createModuleMetadata(ModuleMetadataImpl value) {
    return new JAXBElement<ModuleMetadataImpl>(_ModuleMetadata_QNAME, ModuleMetadataImpl.class,
        null, value);
  }

}
